//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crosshelper {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crosshelper.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Launching {
            get {
                return ResourceManager.GetString("Launching", resourceCulture);
            }
        }
        
        internal static string LaunchingLabel {
            get {
                return ResourceManager.GetString("LaunchingLabel", resourceCulture);
            }
        }
        
        internal static string GetStart {
            get {
                return ResourceManager.GetString("GetStart", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        internal static string EnterPhoneLabel {
            get {
                return ResourceManager.GetString("EnterPhoneLabel", resourceCulture);
            }
        }
        
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        internal static string SMSVerify {
            get {
                return ResourceManager.GetString("SMSVerify", resourceCulture);
            }
        }
        
        internal static string SMSVerifyLabel {
            get {
                return ResourceManager.GetString("SMSVerifyLabel", resourceCulture);
            }
        }
        
        internal static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        internal static string GetHelp {
            get {
                return ResourceManager.GetString("GetHelp", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        internal static string Safety {
            get {
                return ResourceManager.GetString("Safety", resourceCulture);
            }
        }
        
        internal static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        internal static string PastCase {
            get {
                return ResourceManager.GetString("PastCase", resourceCulture);
            }
        }
        
        internal static string MyLanguage {
            get {
                return ResourceManager.GetString("MyLanguage", resourceCulture);
            }
        }
        
        internal static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        internal static string AddPromo {
            get {
                return ResourceManager.GetString("AddPromo", resourceCulture);
            }
        }
        
        internal static string PLanguage {
            get {
                return ResourceManager.GetString("PLanguage", resourceCulture);
            }
        }
        
        internal static string SLanguage {
            get {
                return ResourceManager.GetString("SLanguage", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string CaseInfo {
            get {
                return ResourceManager.GetString("CaseInfo", resourceCulture);
            }
        }
        
        internal static string Helper {
            get {
                return ResourceManager.GetString("Helper", resourceCulture);
            }
        }
        
        internal static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        internal static string ServiceFee {
            get {
                return ResourceManager.GetString("ServiceFee", resourceCulture);
            }
        }
        
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        internal static string EquipmentFee {
            get {
                return ResourceManager.GetString("EquipmentFee", resourceCulture);
            }
        }
        
        internal static string CycbisFee {
            get {
                return ResourceManager.GetString("CycbisFee", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string PaymentInfo {
            get {
                return ResourceManager.GetString("PaymentInfo", resourceCulture);
            }
        }
        
        internal static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        internal static string AccountSetting {
            get {
                return ResourceManager.GetString("AccountSetting", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        internal static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        internal static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        internal static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        internal static string BasePrice {
            get {
                return ResourceManager.GetString("BasePrice", resourceCulture);
            }
        }
        
        internal static string ReviewA {
            get {
                return ResourceManager.GetString("ReviewA", resourceCulture);
            }
        }
        
        internal static string BaseInfoLabel {
            get {
                return ResourceManager.GetString("BaseInfoLabel", resourceCulture);
            }
        }
        
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        internal static string Specialities {
            get {
                return ResourceManager.GetString("Specialities", resourceCulture);
            }
        }
        
        internal static string GH_Title {
            get {
                return ResourceManager.GetString("GH_Title", resourceCulture);
            }
        }
        
        internal static string GH_Q1 {
            get {
                return ResourceManager.GetString("GH_Q1", resourceCulture);
            }
        }
        
        internal static string GH_Q2 {
            get {
                return ResourceManager.GetString("GH_Q2", resourceCulture);
            }
        }
        
        internal static string GH_Q3 {
            get {
                return ResourceManager.GetString("GH_Q3", resourceCulture);
            }
        }
        
        internal static string GH_Q4 {
            get {
                return ResourceManager.GetString("GH_Q4", resourceCulture);
            }
        }
        
        internal static string ServiceInfo {
            get {
                return ResourceManager.GetString("ServiceInfo", resourceCulture);
            }
        }
        
        internal static string FbZ {
            get {
                return ResourceManager.GetString("FbZ", resourceCulture);
            }
        }
        
        internal static string SAZ {
            get {
                return ResourceManager.GetString("SAZ", resourceCulture);
            }
        }
        
        internal static string LP {
            get {
                return ResourceManager.GetString("LP", resourceCulture);
            }
        }
        
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
    }
}
